### ISSUE TITLE
스터디 내부 화면 구현

### ISSUE THREAD

**Issue by harugi7** [kakao-tech-campus-2nd-step3/Team12_FE#42]
## 어떤 기능인가요?
지난 회의에서 정한 스터디 내부 페이지를 구현해야합니다.

## To-Do
- [ ] 스터디 소개 섹션
- [ ] 공지, 출석일, 과제 섹션
- [ ] 달력 섹션
- [ ] 모집 여부 버튼
- [ ] 스터디원 소개 섹션
- [ ] 스터디원 초대하기 버튼
